import mongoose from "mongoose";

/**
 * Document.js
 * -----------
 * PURPOSE:
 *   Stores metadata for every uploaded legal document.
 *   The actual file is stored on disk (uploads/documents/).
 *   This collection stores everything about the file EXCEPT the bytes.
 *
 * WHY A SEPARATE COLLECTION (not embedded in User or Case)?
 *   1. SCALE: One user can have dozens of documents. Embedding large arrays
 *      in a User document makes it huge — MongoDB has a 16MB doc size limit.
 *   2. INDEPENDENT QUERYING:
 *      "All documents for case X" — Case.findById doesn't need to be involved.
 *      "All identity documents for user Y" — direct query on this collection.
 *      "All documents uploaded this month" — admin analytics, no joins needed.
 *   3. FLEXIBILITY: A document can exist without a case (uploaded before case creation)
 *      and can later be linked to a case. Embedding makes this relationship rigid.
 *
 * SOFT DELETE DESIGN:
 *   isDeleted: true hides the document from all user-facing queries.
 *   The physical file on disk IS deleted to free storage.
 *   The metadata record is preserved as an audit trail.
 *   WHY? A document referenced in an active case or court proceeding
 *   must not vanish from history even if the user "deletes" it.
 *
 * FILE ACCESS PATTERN:
 *   filePath stores a URL like: /uploads/documents/1721234567890-482951234-aadhaar.pdf
 *   Express serves this via app.use("/uploads", express.static("uploads")) in server.js
 *   Frontend accesses file: http://localhost:5000/uploads/documents/filename.pdf
 */
const documentSchema = new mongoose.Schema(
  {
    // ─── OWNERSHIP ───────────────────────────

    // Who uploaded this document — always from JWT (req.user.id)
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Which case this document belongs to (optional)
    // WHY optional? Users upload documents before cases are created
    // (identity documents, Aadhaar, PAN etc.)
    // Once a case is created, the user can link documents to it.
    caseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Case",
      default: null,
    },

    // ─── FILE IDENTITY ────────────────────────

    // The original filename the user uploaded e.g. "aadhaar-card.pdf"
    // Stored so the UI shows the user's own filename, not the generated one.
    originalName: {
      type: String,
      required: true,
    },

    // The unique filename generated by Multer on disk
    // Format: {timestamp}-{random9}-{sanitised-name}{ext}
    // Used internally to build the file path and to delete the file from disk.
    fileName: {
      type: String,
      required: true,
    },

    // Full URL path to access the file via Express static
    // Example: /uploads/documents/1721234567890-482951234-aadhaar-card.pdf
    // Frontend appends this to the base URL: http://localhost:5000 + filePath
    filePath: {
      type: String,
      required: true,
    },

    // MIME type of the file e.g. "application/pdf", "image/jpeg"
    // Frontend uses this to decide rendering:
    //   application/pdf → open in PDF viewer
    //   image/* → render as <img> tag
    //   application/msword → show download-only (no preview)
    fileType: {
      type: String,
      required: true,
    },

    // File size in bytes (set by Multer from req.file.size)
    // Stored so the UI can display "2.4 MB" without loading the file.
    // Conversion: bytes / 1024 / 1024 = MB
    fileSize: {
      type: Number,
      required: true,
    },

    // ─── CLASSIFICATION ───────────────────────

    // Category of the document — helps users organise their vault
    // enum enforces consistency — filtering by category always works exactly.
    // These 7 categories cover all common legal document types.
    category: {
      type: String,
      required: true,
      enum: [
        "Identity Document",  // Aadhaar, PAN, Passport, Driving Licence
        "Court Document",     // FIR, Bail Order, Judgment, Summons
        "Legal Notice",       // Notices, RTI Applications, Cease & Desist
        "Agreement",          // Rent Agreement, Sale Deed, MOU, Contract
        "Evidence",           // Photos, Witness Statements, CCTV footage
        "Case Related",       // Case-specific documents tied to a specific case
        "Other",              // Anything that doesn't fit the above
      ],
    },

    // Optional description/note about this document
    // e.g. "Original property deed purchased in 1998, Lucknow"
    description: {
      type: String,
      default: "",
      trim: true,
    },

    // ─── SOFT DELETE ──────────────────────────

    // Soft delete flag — true = document is "deleted" from user's view
    // WHY SOFT DELETE?
    //   Legal documents may be referenced in active cases or court proceedings.
    //   Hard-deleting a document linked to a live case is dangerous.
    //   isDeleted: true hides it from all user queries via { isDeleted: false } filter.
    //   The physical file on disk IS deleted to recover storage.
    //   The metadata record stays as an audit trail.
    isDeleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true, // Auto-adds createdAt (upload date) and updatedAt
  }
);

// ─────────────────────────────────────────────
// INDEXES for fast querying
// ─────────────────────────────────────────────
// userId index: fast lookup of "all documents for this user" — most common query
documentSchema.index({ userId: 1 });
// caseId index: fast lookup of "all documents for this case"
documentSchema.index({ caseId: 1 });
// compound index: fast filtered queries like "all PDFs for user X"
documentSchema.index({ userId: 1, category: 1 });

const Document = mongoose.model("Document", documentSchema);

export default Document;
